# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signalGenerator.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(945, 736)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/PythonFinalwork/pythonfinal/窗口图标.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox1.setGeometry(QtCore.QRect(40, 30, 571, 391))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox1.setFont(font)
        self.groupBox1.setObjectName("groupBox1")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 501, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.zoomin_Button = QtWidgets.QPushButton(self.groupBox1)
        self.zoomin_Button.setGeometry(QtCore.QRect(520, 20, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomin_Button.sizePolicy().hasHeightForWidth())
        self.zoomin_Button.setSizePolicy(sizePolicy)
        self.zoomin_Button.setMinimumSize(QtCore.QSize(40, 40))
        self.zoomin_Button.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.zoomin_Button.setFont(font)
        self.zoomin_Button.setStyleSheet("QPushButton{\n"
"\n"
"        color: black;   \n"
"        border-radius:20px;  \n"
"        border: 3px groove gray;\n"
"        border-style: outset;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 rgb(255, 225, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"}\n"
"\n"
"")
        self.zoomin_Button.setIconSize(QtCore.QSize(20, 20))
        self.zoomin_Button.setObjectName("zoomin_Button")
        self.zoomout_Button = QtWidgets.QPushButton(self.groupBox1)
        self.zoomout_Button.setGeometry(QtCore.QRect(520, 70, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomout_Button.sizePolicy().hasHeightForWidth())
        self.zoomout_Button.setSizePolicy(sizePolicy)
        self.zoomout_Button.setMinimumSize(QtCore.QSize(40, 40))
        self.zoomout_Button.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.zoomout_Button.setFont(font)
        self.zoomout_Button.setStyleSheet("QPushButton{\n"
"\n"
"        color: black;   \n"
"        border-radius:20px;  \n"
"        border: 3px groove gray;\n"
"        border-style: outset;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 rgb(255, 225, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"}")
        self.zoomout_Button.setIconSize(QtCore.QSize(20, 20))
        self.zoomout_Button.setObjectName("zoomout_Button")
        self.groupBox2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox2.setGeometry(QtCore.QRect(40, 440, 571, 221))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox2.setFont(font)
        self.groupBox2.setObjectName("groupBox2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(250, 0, 311, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.signalAmplitude = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.signalAmplitude.setObjectName("signalAmplitude")
        self.gridLayout.addWidget(self.signalAmplitude, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.signalPhase = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.signalPhase.setObjectName("signalPhase")
        self.gridLayout.addWidget(self.signalPhase, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.signalPeriod = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.signalPeriod.setObjectName("signalPeriod")
        self.gridLayout.addWidget(self.signalPeriod, 0, 1, 1, 1)
        self.signalBaseline = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.signalBaseline.setObjectName("signalBaseline")
        self.gridLayout.addWidget(self.signalBaseline, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.groupBox2)
        self.splitter.setGeometry(QtCore.QRect(110, 20, 121, 81))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.label.setObjectName("label")
        self.signalType = QtWidgets.QComboBox(self.splitter)
        self.signalType.setEditable(False)
        self.signalType.setCurrentText("")
        self.signalType.setObjectName("signalType")
        self.signalType.addItem("")
        self.signalType.addItem("")
        self.signalType.addItem("")
        self.signalType.addItem("")
        self.basic_signal = QtWidgets.QCheckBox(self.groupBox2)
        self.basic_signal.setGeometry(QtCore.QRect(10, 70, 91, 19))
        self.basic_signal.setObjectName("basic_signal")
        self.ecg_signal = QtWidgets.QCheckBox(self.groupBox2)
        self.ecg_signal.setGeometry(QtCore.QRect(10, 160, 91, 19))
        self.ecg_signal.setObjectName("ecg_signal")
        self.ecg_valueSlider = QtWidgets.QSlider(self.groupBox2)
        self.ecg_valueSlider.setGeometry(QtCore.QRect(280, 160, 221, 31))
        self.ecg_valueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ecg_valueSlider.setObjectName("ecg_valueSlider")
        self.ecg_valueText = QtWidgets.QLabel(self.groupBox2)
        self.ecg_valueText.setGeometry(QtCore.QRect(140, 160, 111, 16))
        self.ecg_valueText.setObjectName("ecg_valueText")
        self.groupBox3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox3.setGeometry(QtCore.QRect(630, 30, 271, 631))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox3.setFont(font)
        self.groupBox3.setObjectName("groupBox3")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox3)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 60, 171, 491))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout2.setObjectName("verticalLayout2")
        self.dynamicButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.dynamicButton.setFont(font)
        self.dynamicButton.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 rgb(255, 225, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"}\n"
"")
        self.dynamicButton.setObjectName("dynamicButton")
        self.verticalLayout2.addWidget(self.dynamicButton)
        self.addButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.addButton.setFont(font)
        self.addButton.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 rgb(255, 225, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"}")
        self.addButton.setObjectName("addButton")
        self.verticalLayout2.addWidget(self.addButton)
        self.filterButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.filterButton.setFont(font)
        self.filterButton.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 rgb(255, 225, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"}")
        self.filterButton.setObjectName("filterButton")
        self.verticalLayout2.addWidget(self.filterButton)
        self.syntheticButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.syntheticButton.setFont(font)
        self.syntheticButton.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 rgb(255, 225, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"}")
        self.syntheticButton.setObjectName("syntheticButton")
        self.verticalLayout2.addWidget(self.syntheticButton)
        self.spectrumButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.spectrumButton.setFont(font)
        self.spectrumButton.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0.909, y1:0.864, x2:0.926, y2:0, stop:0.448864 rgb(255, 225, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"}")
        self.spectrumButton.setObjectName("spectrumButton")
        self.verticalLayout2.addWidget(self.spectrumButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 945, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuQuit = QtWidgets.QMenu(self.menubar)
        self.menuQuit.setObjectName("menuQuit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionInstruct = QtWidgets.QAction(MainWindow)
        self.actionInstruct.setObjectName("actionInstruct")
        self.menu.addAction(self.actionSave)
        self.menuQuit.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionInstruct)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuQuit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.signalType.setCurrentIndex(-1)
        self.actionQuit.triggered.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "医用心电多功能信号发生器"))
        self.groupBox1.setTitle(_translate("MainWindow", "信号波形"))
        self.zoomin_Button.setText(_translate("MainWindow", "+"))
        self.zoomout_Button.setText(_translate("MainWindow", "-"))
        self.groupBox2.setTitle(_translate("MainWindow", "参数设置"))
        self.signalAmplitude.setText(_translate("MainWindow", "2.0"))
        self.label_2.setText(_translate("MainWindow", "信号周期"))
        self.signalPhase.setText(_translate("MainWindow", "2.0"))
        self.label_3.setText(_translate("MainWindow", "信号基线"))
        self.signalPeriod.setText(_translate("MainWindow", "4.0"))
        self.signalBaseline.setText(_translate("MainWindow", "1.0"))
        self.label_4.setText(_translate("MainWindow", "信号幅值"))
        self.label_5.setText(_translate("MainWindow", "信号时移"))
        self.label.setText(_translate("MainWindow", "          信号类型"))
        self.signalType.setItemText(0, _translate("MainWindow", "正弦波"))
        self.signalType.setItemText(1, _translate("MainWindow", "三角波"))
        self.signalType.setItemText(2, _translate("MainWindow", "锯齿波"))
        self.signalType.setItemText(3, _translate("MainWindow", "方波"))
        self.basic_signal.setText(_translate("MainWindow", "基本信号"))
        self.ecg_signal.setText(_translate("MainWindow", "心电信号"))
        self.ecg_valueText.setText(_translate("MainWindow", "心率值："))
        self.groupBox3.setTitle(_translate("MainWindow", "功能设置"))
        self.dynamicButton.setText(_translate("MainWindow", "动态演示"))
        self.addButton.setText(_translate("MainWindow", "添加噪声"))
        self.filterButton.setText(_translate("MainWindow", "进行滤波"))
        self.syntheticButton.setText(_translate("MainWindow", "合成信号"))
        self.spectrumButton.setText(_translate("MainWindow", "生成频谱"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menuQuit.setTitle(_translate("MainWindow", "退出"))
        self.menuHelp.setTitle(_translate("MainWindow", "帮助"))
        self.actionOpen.setText(_translate("MainWindow", "打开"))
        self.actionSave.setText(_translate("MainWindow", "保存"))
        self.actionQuit.setText(_translate("MainWindow", "退出"))
        self.actionInstruct.setText(_translate("MainWindow", "使用说明"))
